version: "3"
services:
  avocado:
    build: .
    ports:
      - "8080:8080"
    environment:
      CLIENT_ID: 
      CLIENT_SECRET: 
      DB_HOST: 
      DB_USER: 
      DB_KEY: 
      DB_DB: 
      REDIRECT_URL:
      PORT: 8080
